### ISSUE TITLE
Anti Weapon can't detect this cleo

### ISSUE THREAD

**Issue by tintrongveo** [RogueDrifter/Anti_cheat_pack#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like you to make a anticheat which can fight against this cleo.

**Describe alternatives you've considered**
[LINK REMOVED] 
Reason: Downloadable cheat (I already viewed it)

**Additional context**
no.

**Comment by RogueDrifter** [comment]
Looks like a normal weapon cheat to me, make sure you're updated to the latest version of the anti cheat pack and test it again. I'll leave the issue open for a couple of days and close it if i dont get a reply.
