### ISSUE TITLE
An oversight in rEac.inc

### ISSUE THREAD

**Issue by Daniel-Cortez** [RogueDrifter/Anti_cheat_pack#17]
**Describe the bug**
The following code in function `OnPlayerUpdate()` (`rEac.inc`) looks suspicious:
https://github.com/RogueDrifter/Anti_cheat_pack/blob/c8359136da7901e98dad1860e03f0d581381e5ff/rEac.inc#L169-L173
Variable `EacTempSCar` is used before being assigned a value (zero-initialized by default), so the condition
```Pawn
GetPlayerState(playerid) == PLAYER_STATE_DRIVER && EacTempSCar != GetPlayerVehicleID(playerid)
```
works as
```Pawn
GetPlayerState(playerid) == PLAYER_STATE_DRIVER && 0 != GetPlayerVehicleID(playerid)
```
which doesn't make a lot of sense because `GetPlayerVehicleID()` never returns `0` if the player is driving a vehicle (`PLAYER_STATE_DRIVER`).

You'll probably want to to assign some value to `EacTempSCar` before using the variable inside an `if` expression, or just remove it completely.

**To Reproduce**
–

**Expected behavior**
–

**Screenshots**
–

**Samp details (please complete the following information):**
 - Version: [e.g. 0.3.7/0.3.7-R2]
 - Using filterscripts? [Yes/No]
 - Using sampctl? [Yes/No]

**Additional context**
–

**Comment by RogueDrifter** [comment]
Yeah you're totally right i dunno why that's there i probably was sleepy or something or maybe that's some of lorenc_'s code most of it is his anyways, thanks for the notes.
