### ISSUE TITLE
Fix line endings 

### ISSUE THREAD

**Issue by BigETI** [RogueDrifter/Anti_cheat_pack#2]
Avoid pushing carriage return characters.

**Comment by cactysman** [comment]
Note the red `^M` in this example if you don't know what @BigETI meant: 
 https://github.com/RogueDrifter/Anti_cheat_pack/blob/051efcc87a587949828c1310e116e14f23881b89/AntiFC.inc#L1-L69

This is the case for **most** of the files.

**Comment by RogueDrifter** [comment]
Ik what he meant i'll work on it, shouldnt be a problem as it doesn't affect anything other than the view of the file through the github interface.

**Comment by RogueDrifter** [comment]
Fixed it.
