### ISSUE TITLE
AirbreakTeleport.inc Detection Issue

### ISSUE THREAD

**Issue by v0UwUK6CmCrjVB1PAtRb** [RogueDrifter/Anti_cheat_pack#22]
**Describe the bug**
Sometimes, when going between world 0 and a virtual world (1000) in interior ID 1 (Warehouse 1) (and quite possibly vice-versa, I can't be sure of that), AirbreakTeleport.inc will be triggered. I should add that I'm also using LaggersDetect.inc.

**To Reproduce**
It is hard to give steps as it doesn't always happen, but the basic overview of what causes the issue is written above. 

**Expected behavior**
AirbreakTeleport.inc should not flag the player(s). 

**Screenshots**
N/A

**Samp details (please complete the following information):**
 - Version: 0.3.7-R2
 - Using filterscripts? Yes
 - Using sampctl? No

**Additional context**
N/A

**Comment by RogueDrifter** [comment]
Did you include the include in all of your filterscripts? 
And for future reference could you possibly print out the callback parameters?
```
public OnPlayerBreakAir(playerid, breaktype)
{
    printf("playerid %d breaktype %d", playerid, breaktype);
    return 1;
}
```
