### ISSUE TITLE
Some kind of attackings.

### ISSUE THREAD

**Issue by emadelanwar** [RogueDrifter/Anti_cheat_pack#27]
Hello,
My server faced multiple kinds of attacking, such as server restarting, changing scores and many more!
A hacker could kick someone playing even without being in-game!
A normal player told me he has Sobiet, he could restart the server in no moment!
How can i secure this from happening again?
Thanks a lot.

**Comment by RogueDrifter** [comment]
My friend, this is a repository not a forum thread, please post your issue on burgershot forum to get help.
