### ISSUE TITLE
Script didn't do anything

### ISSUE THREAD

**Issue by difaananda40** [RogueDrifter/Anti_cheat_pack#28]
**Describe the bug**
I implemet this include on bare gamemde, and the scripts seems didn't do anything

**Comment by RogueDrifter** [comment]
You need to be more specific, I haven't played in years but I'm still familiar with my work, what cheat did you use and what package did you include, give full details

**Comment by difaananda40** [comment]
Im just using this include, and try with or without callback in my gm, the script didnt do anything

**Comment by RogueDrifter** [comment]
The script has 15 includes, i don't think you know what you're talking about, open a new issue with full documentation, the script was tested and it works, give proper documentation or ask someone on how to use includes and compile a script properly
