### ISSUE TITLE
AIRBREAK NO DETECT

### ISSUE THREAD

**Issue by Necroxy** [RogueDrifter/Anti_cheat_pack#29]
**Describe the bug**
AIRBREAK no detect

**To Reproduce**
-

**Expected behavior**

**Screenshots**
public OnPlayerViolate(playerid, severity, violationCode, const violationName[])
{
	new acString[128], name[MAX_PLAYER_NAME];
	GetPlayerName(playerid, name, sizeof name);
	
	switch(violationCode)
	{
		case VIOLATION_CODE_CHATSPAM:
		{
			Info(playerid, "Lu olang spam");
			KickEx(playerid);
		}
		case VIOLATION_CODE_AIRBRAKE:
		{
			Info(playerid, "Lu olang airbrake");
			KickEx(playerid);
		}
	}
	return 1;
}

**Samp details (please complete the following information):**
 - Version: [e.g. 0.3.7/0.3.7-R2]
 - Using filterscripts? [Yes/No]
 - Using sampctl? [Yes/No]

**Additional context**

**Comment by RogueDrifter** [comment]
Unclear provide a video + hack u used
